src/helpers/portfolio/portfolio-helper-s.ts
src/routing/catalog-route-s.js
src/smart-components/portfolio/portfolios.js
src/standalone-nav.js
src/test/smart-components/portfolio/portfolio-item-detail/edit-portfolio-item-s.test.js

- Fix portfolios list double render
- Redirect to login when /auth/me returns 403
- Fixes the portfolio item edit
Fixes 
- https://issues.redhat.com/browse/SSP-2731
- https://issues.redhat.com/browse/SSP-2691
- https://issues.redhat.com/browse/SSP-2633

Fix portfolios list double render. Redirect to login when /auth/me returns 403

---

src/forms/portfolio-form.schema.ts
src/smart-components/portfolio/add-portfolio-modal.tsx
src/standalone-nav.js
src/test/smart-components/common/edit-approval-workflow-s.test.js

Fixes https://issues.redhat.com/browse/SSP-2630
Update portfolio name validator.

Update portfolio name validator

---

src/App.js
src/helpers/shared/active-user.ts
src/presentational-components/shared/loader-placeholders.tsx
src/routing/catalog-route-s.js
src/standalone-nav.js

Fixes https://issues.redhat.com/browse/SSP-2779

Update error handling on auth/me

---

config/standalone.dev.webpack.config.js
src/helpers/shared/user-login.ts
src/standalone-nav.js
src/test/helpers/shared/user-login.test.js
src/utilities/store.ts

Updated notification middleware configuration. 
Updated path for dev distribution build

Fixed error notifcations

---

config/setupTests.js
config/standalone.prod.webpack.config.js
config/webpack.base.config.js
src/index.html
src/standalone-nav.js
src/utilities/constants.ts

Title from command line variable APPLICATION_NAME:

Update application name to use env. variable

---

config/standalone.prod.webpack.config.js
src/smart-components/portfolio/share-portfolio-modal.tsx
src/test/smart-components/portfolio/share-portfolio-modal.test.js
src/utilities/constants.ts

https://issues.redhat.com/browse/SSP-2752
Added 'delete' verb to the share permissions
Share with order/edit:
Update from order/edit to order/view
Unshare of order/edit

Update share permision verbs

---

config/standalone.prod.webpack.config.js
src/messages/portfolio.messages.ts
src/redux/actions/portfolio-actions-s.tsx
src/smart-components/portfolio/share-portfolio-modal.tsx
src/test/smart-components/portfolio/share-portfolio-modal.test.js
src/utilities/constants.ts

https://issues.redhat.com/browse/SSP-2741

Remove the Undo option from the delete portfolio notification

---

src/smart-components/products/products.js

https://issues.redhat.com/browse/SSP-2692

[SSP-2692] Fixed product link in the product card

---

README.md

Updated the README a bit. I wasn't sure if we still needed the Insights-Proxy piece, but I'm guessing we don't. If that's the case, I'll remove it but wanted to confirm first.

Update README to adjust naming to Pinakes; Replace old badges

---

src/standalone-nav.js

Changed classname to className

---

src/helpers/order/service-plan-helper-s.ts
src/test/helpers/order/service-plan-helper.test.js

[SSP-2852] Fix survey reset

---

package.json
src/messages/order-processes.messages.ts
src/messages/workflows.messages.js

Ignore the test directory
Fixes #90

Removed duplicate messages

---

src/standalone-nav.js

Add parameters to the 'next' parameter url for login.

[SSP-2904] Fixed the next url parameter for loginUser

---

locales/es/messages.json
locales/fr/messages.json
locales/ja/messages.json
locales/ko/messages.json
locales/nl/messages.json
locales/zh/messages.json

@lgalis These are the initial translated UI strings.  Currently, es and nl are incomplete.  I will work with the translators to get that resolved, but figured I should commit these so that you can get have something to work with for now.  
I think that we can cherry-pick this back to the stable/1.0 branch because it is the initial commit for translated strings.

Localization: Add initial translated strings

---

locales/es/messages.json
locales/fr/messages.json
locales/ja/messages.json
locales/ko/messages.json
locales/nl/messages.json
locales/zh/messages.json

Related PR for main: https://github.com/ansible/pinakes-ui/pull/94
These are the initial translated strings for the pinakes UI's stable branch.

Localization: Add initial translated strings [stable]

---

src/test/smart-components/platform/platform-inventories.test.js
src/utilities/constants.ts

https://issues.redhat.com/browse/SSP-2931
Change the app-name to match the backend's expectation.

[SSP-2931] Change app_name for inventory from catalog-inventory to inventory

---

package-lock.json
package.json

Reverse the update to the frontend components to fix the dist build.

Reverse frontend component package update to fix the dist build

---

src/forms/add-notification.schema.js
src/smart-components/notification-settings/edit-notification-setting-modal.js
src/smart-components/notification-settings/remove-notification-setting-modal.js
src/smart-components/template/remove-template-modal.js
src/test/smart-components/notification-settings/modals/__snapshots__/edit-notification-setting-modal.test.js.snap
src/test/smart-components/notification-settings/modals/edit-notification-setting-modal.test.js

To be merged after #99 
Fixes:
- refresh after edit
- delete
Added tests for the edit notification setting modal.

Fixes for the edit notification setting modal

---

src/forms/add-template.schema.js
src/forms/load-notification_settings-debounced.js
src/helpers/notification/notification-helper.js
src/messages/templates.messages.js
src/smart-components/template/add-template-modal.js
src/smart-components/template/edit-template-modal.js
src/smart-components/template/remove-template-modal.js
src/test/smart-components/template/modals/edit-template-modal.test.js
src/test/smart-components/template/templates.test.js

[SSP-2941] Add notifications to the create/edit templates modals

---

src/forms/add-template.schema.js
src/forms/add-workflow.schema.js
src/forms/load-templates-debounced.js
src/forms/set-template-select.schema.js
src/helpers/template/template-helper.js
src/helpers/workflow/workflow-helper.js
src/messages/templates.messages.js
src/messages/workflows.messages.js
src/smart-components/workflow/add-workflow-modal.js
src/smart-components/workflow/edit-workflow-modal.js
src/test/smart-components/template/modals/edit-template-modal.test.js
src/test/smart-components/template/templates.test.js
src/test/smart-components/workflow/modals/add-workflow-modal-s.test.js
src/test/smart-components/workflow/modals/edit-workflow-modal.test.js
src/test/smart-components/workflow/workflows.test.js

To be merged after #108
Add template selection to the create/edit workflow modals:

[SSP-2942] Add template selection to the create/edit workflow modals

---

src/forms/approval-name-async-validator.js
src/helpers/group/group-helper.js
src/helpers/template/template-helper.js
src/helpers/workflow/workflow-helper.js
src/smart-components/workflow/add-workflow-modal.js
src/test/smart-components/template/templates.test.js
src/test/smart-components/workflow/modals/add-workflow-modal-s.test.js
src/test/smart-components/workflow/modals/edit-workflow-modal.test.js
src/test/smart-components/workflow/workflows.test.js

Adds approval-admin role to the group query:
The new query is : 
https://catalog.k8s.local/api/pinakes/v1/groups/?role=approval-approver&role=approval-admin

[SSP-2756] Update group query

---

src/standalone-nav.js
src/utilities/constants.ts

Added a constant for the catalog prefix. 
Redirect to the default catalog path on logout.
Also fixes SSP-2809

[SSP-2921] Redirect to the catalog default page on logout

---

src/global-styles.js

Jira: https://issues.redhat.com/browse/RHCLOUD-19815
Update Nav header styling
Old
New

Update nav styling

---

package-lock.json
package.json

Reverts ansible/pinakes-ui#129

Revert "Bump @redhat-cloud-services/frontend-components-config from 4.6.8 to 4.6.14"

---

src/global-styles.js

Jira: https://issues.redhat.com/browse/RHCLOUD-19815
Add PF variables, etc

styling cleanup

---

src/presentational-components/portfolio/portfolio-card.tsx
src/redux/reducers/portfolio-reducer.ts
src/smart-components/notification-settings/edit-notification-setting-modal.js
src/smart-components/platform/platforms.js
src/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.js
src/smart-components/portfolio/portfolio-item-detail/portfolio-item-detail.js
src/smart-components/portfolio/portfolio-items.js
src/smart-components/portfolio/portfolio.js
src/smart-components/portfolio/portfolios.js
src/smart-components/portfolio/remove-portfolio-modal.tsx
src/smart-components/products/products.js
src/standalone-nav.js
src/test/helpers/approval/approval-helper-s.test.js
src/test/integration/portfolio-share-workflow.test.js
src/test/presentational-components/portfolio/__snapshots__/portfolio-card.test.js.snap
src/test/presentational-components/portfolio/portfolio-card.test.js
src/test/smart-components/common/edit-approval-workflow-s.test.js
src/test/smart-components/order/orders.test.js
src/test/smart-components/portfolio/portfolio-item-detail/__snapshots__/detail-toolbar-actions.test.js.snap
src/test/smart-components/portfolio/portfolio-item-detail/detail-toolbar-actions.test.js
src/test/smart-components/portfolio/portfolios.test.js
src/test/smart-components/products/products.test.js
src/test/smart-components/workflow/modals/edit-workflow-modal.test.js
src/test/utilities/portfolio-toolbar.schema.test.js
src/toolbar/schemas/portfolio-toolbar.schema.js
src/types/common-types-s.d.ts
src/types/common-types.d.ts
src/utilities/constants.ts

Reenable user capabilities
